language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq libssl-dev libcunit1-dev libcppunit-dev
install:
  - ./autogen.sh
env:
  - FLAGS=--enalbe-debug
  - FLAGS=
script: 
  - mkdir -p build
  - cd build 
  - ../configure $FLAGS
  - make -j 2
  - make -j 2 check
